import dynamic from "next/dynamic";
import "./globals.css";
import { Inter, Montserrat } from "next/font/google";
import { Toaster } from "react-hot-toast";
const Navbar = dynamic(() => import("../components/Navbar"), {ssr : false});
import WebSocketContext, { WebSocketProvider } from '../lib/MessageContext';

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LEAFBOX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} max-h-screen h-screen relative flex flex-col`}
      >
        <Navbar />

        <main className="overflow-auto h-full bg-white text-black flex-1">
          <div>
            <Toaster
              position="top-right"
              toastOptions={{
                style: {
                  background: "#222",
                  color: "#fff",
                },
              }}
            />
          </div>
          <WebSocketProvider>
            {children}
          </WebSocketProvider>
        </main>
      </body>
    </html>
  );
}
