import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import WebSocketProvider from "../lib/MessageContext";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { cookies } from "next/headers";
import { ClientCookiesProvider } from "@/utils/CookieProvider";
import AppContextProvider from "@/utils/AppContextProvider";
import { Suspense } from "react";
import Loading from "./loading";
import Navbar from "@/components/Navbar";
import { TooltipProvider } from "@/components/ui/tooltip";

config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LEAFBOX",
  description: "Generated by create next app",
  viewport:
    "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body
        className={`${inter.className} max-h-screen min-h-screen w-screen relative flex gap-3 overflow-hidden`}
      >
        <Toaster
          position="top-right"
          toastOptions={{
            style: {
              background: "#09090b",
              color: "#fff",
              border: "1px solid 	#27272a",
              borderRadius: "0.5rem",
              padding: "1.5rem",
            },
            position: "bottom-right",
          }}
        />
        <WebSocketProvider />
        <ClientCookiesProvider value={cookies().getAll()}>
          <AppContextProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <TooltipProvider>
            <div className="w-full mx-auto flex flex-col box-border">
              <Navbar />
              <main className="max-w-[1920px] w-full mx-auto flex-1 space-y-4 p-2 md:p-8 pt-6 overflow-y-auto">
                <Suspense fallback={<Loading />}>{children}</Suspense>
              </main>
            </div>
          </TooltipProvider>
          </AppContextProvider>
        </ClientCookiesProvider>
      </body>
    </html>
  );
}
