import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Sidebar from "@/components/Sidebar";
import Background from "@/components/Background";
import WebSocketProvider from "../lib/MessageContext";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Searchbar from "@/components/Searchbar";
import Loader from "@/components/Loader/Loader";
config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LEAFBOX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} max-h-screen h-screen relative flex p-8 gap-3 overflow-hidden`}
      >
        <Background />
        <Loader />
        <Toaster
          position="top-right"
          toastOptions={{
            style: {
              background: "#222",
              color: "#fff",
              borderRadius: "99px",
            },
            position: "top-center",
          }}
        />
        <WebSocketProvider />
        <div className="max-w-7xl mx-auto flex-1 flex gap-3">
          <Sidebar />
          <div className="h-full flex-1 flex flex-col gap-3">
            <Searchbar />
            <main className="flex-1 overflow-y-auto">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
